export const TyphoonLegend = [
    {
        headline:"台风等级",
        label:[
            {
                title:"热带低压",
                bg:"#00cc99",
                value:"TD"
            },
            {
                title:"热带风暴",
                bg:"#00ff00",
                value:"TS"
            },
            {
                title:"强热带风暴",
                bg:"#ccff00",
                value:"STS"
            },
            {
                title:"台风",
                bg:"#fdb700",
                value:"TY"
            },
            {
                title:"强台风",
                bg:"#fd5c1c",
                value:"STY"
            },
            {
                title:"超强台风",
                bg:"#fd0026",
                value:"SuperTY"
            }
        ]
    }
];
export const AreaLegend = [
    {
        headline:"沿海5省50年一遇最大风速(m/s)",
        label:[
            {
                title:"<37.5",
                bg:"#4575b5"
            },
            {
                title:"37.5~42.5",
                bg:"#8da5ba"
            },
            {
                title:"42.5~46",
                bg:"#d9e0bf"
            },
            {
                title:"46~50",
                bg:"#fcdd9a"
            },
            {
                title:"50~53",
                bg:"#f08159"
            },
            {
                title:">53",
                bg:"#d73f2a"
            }

        ]
    },
    {
        headline:"沿海5省70米高度年平均风速(m/s)",
        label:[
            {
                title:"<5",
                bg:"#fef980"
            },
            {
                title:"5~6",
                bg:"#fcdd5d"
            },
            {
                title:"6~7",
                bg:"#f7ba3e"
            },
            {
                title:"7~8",
                bg:"#d6852a"
            },
            {
                title:"8~9",
                bg:"#9d441c"
            },
            {
                title:">9",
                bg:"#6b1b10"
            }

        ]
    },
    {
        headline:"沿海5省50年一遇最大风速与平均风速比值",
        label:[
            {
                title:"<5",
                bg:"#51a80a"
            },
            {
                title:"5~6",
                bg:"#6fc411"
            },
            {
                title:"6~7",
                bg:"#b0e021"
            },
            {
                title:"7~8",
                bg:"#fdf733"
            },
            {
                title:"8~9",
                bg:"#f6a931"
            },
            {
                title:"9~10",
                bg:"#ee5130"
            },
            {
                title:">10",
                bg:"#ed462f"
            }
        ]

    }
]
export const PredictionLegend = [
    {
        label:"中国",
        value:"BABJ",
        bg:"#669900"
    },
    {
        label:"美国",
        value:"BCGZ",
        bg:"#00FFFF"
    },
    {
        label:"日本",
        value:"RJTD",
        bg:"#FF99FF"
    }
]

